### ISSUE TITLE
Request new feature multiple translation

### ISSUE THREAD

**Issue by azulkipli** [qzaidi/quran#3]
Request new feature multiple translation so we can get translation in other language?

**Comment by qzaidi** [comment]
Yes, its quite easy to add a new translation. I haven't added them not to increase the npm size, but it is really a matter of modify this variable in scripts/installs

 TRANSLATIONS="en.shakir ur.jawadi hi.hindi"

Which translation are you looking for?

**Comment by infacq** [comment]
Indonesia
